### ISSUE TITLE
VTX

### ISSUE THREAD

**Issue by tannewt** [chickadee-tech/polystack#3]
Create a VTX mod!

**Comment by digitalentity** [comment]
VTX modules have a pretty standard pinout (FX758 and alike), they are usually controlled by 3 pin multiplex (8ch) or 3-pin SPI (32+ ch), so it should be pretty straight-forward to create a board to solder the VTX module on top. The only thing you'll need is a powerful 3.3V power regulator.

**Comment by Roechamboe** [comment]
The pdb I have in works can push out 2 amps to the stack you can step that down to the operating voltage of the vtx module. The only problem with using a prebuilt vtx to solder on to the stack module is the height can only be a max of 4mm I suppose most are probably under 3mm so should be fine.

Edit: I just took measurements a FX758-2 is 2.60 mm high so a 3 mm or 3.5 mm df40 connector would work. Your idea using a prebuilt saves the effort of creating from scratch.

**Comment by tannewt** [comment]
@digitalentity How powerful is powerful?

@Roechamboe You can get around the 4mm restriction by providing a spacer board to go above it. Or, you can require that it go on the top of the stack. :-)

**Comment by Roechamboe** [comment]
@tannewt see edit; a standard 800ma 3.3 LVR in a SOT-223 package should do the trick.

**Comment by tannewt** [comment]
@Roechamboe you need 1.5 more above it though to be compatible. The 1.5mm is reserved for the mod above to put components on the bottom of the board.

**Comment by digitalentity** [comment]
@tannewt 800ma LDO (AMS1117) should be enough to power the VTX, and as VTX tend to generate a lot of heat it's good to have it a top-most board.

**Comment by tannewt** [comment]
Anybody want to draft up a board? :-)

**Comment by tannewt** [comment]
@Roechamboe do you have an FX758 I could buy off of you? I think I'll draft a design next week. Gotta get stuff to OSH Park.

**Comment by tannewt** [comment]
@sheaivey pointed me to this project of his: https://github.com/sheaivey/tx5823-pro

**Comment by tannewt** [comment]
I've created a separate repo for this. Please follow along there. https://github.com/chickadee-tech/vtx
